//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DQA.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class dmp_Organizations
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Address { get; set; }
        public string OrganizationType { get; set; }
        public string MissionPartner { get; set; }
        public byte[] Logo { get; set; }
        public string WebSite { get; set; }
        public string Fax { get; set; }
        public string PhoneNumber { get; set; }
    }
}
