//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DQA.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class dqa_lnk_version_indicators
    {
        public int id { get; set; }
        public int version_id { get; set; }
        public string indicator_code { get; set; }
    
        public virtual dqa_versions dqa_versions { get; set; }
    }
}
