//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DQA.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class dqa_FY17Q1_Analysyis
    {
        public string IP { get; set; }
        public string Facility { get; set; }
        public Nullable<double> DQA_FY17Q1_HTC_TST { get; set; }
        public Nullable<double> Validated_HTC_TST { get; set; }
        public Nullable<double> CR_HTC_TST { get; set; }
        public Nullable<double> DQA_FY17Q1_PMTCT_STAT { get; set; }
        public Nullable<double> Validated_PMTCT_STAT { get; set; }
        public Nullable<double> CR_PMTCT_STAT { get; set; }
        public Nullable<double> DQA_FY17Q1_PMTCT_EID { get; set; }
        public Nullable<double> Validated_PMTCT_EID { get; set; }
        public Nullable<double> CR_PMTCT_EID { get; set; }
        public Nullable<double> DQA_FY17Q1_PMTCT_ARV { get; set; }
        public Nullable<double> Validated_PMTCT_ARV { get; set; }
        public Nullable<double> CR_PMTCT_ARV { get; set; }
        public Nullable<double> DQA_FY17Q1_TX_NEW { get; set; }
        public Nullable<double> Validated_TX_NEW { get; set; }
        public Nullable<double> CR_TX_NEW { get; set; }
        public Nullable<double> DQA_FY17Q1_TX_CURR { get; set; }
        public Nullable<double> Validated_TX_CURR { get; set; }
        public Nullable<double> CR_TX_CURR { get; set; }
        public Nullable<double> Count_Fails { get; set; }
        public int Id { get; set; }
    }
}
