//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DQA.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class dqa_report_value
    {
        public int Id { get; set; }
        public int MetadataId { get; set; }
        public int IndicatorId { get; set; }
        public Nullable<decimal> IndicatorValueMonth1 { get; set; }
        public Nullable<decimal> IndicatorValueMonth2 { get; set; }
        public Nullable<decimal> IndicatorValueMonth3 { get; set; }
    
        public virtual dqa_indicator dqa_indicator { get; set; }
    }
}
