//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DQA.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class dqa_dimensions
    {
        public int Id { get; set; }
        public string FacilityName { get; set; }
        public string FacilityCode { get; set; }
        public string HTC_Charts { get; set; }
        public string PMTCT_STAT_charts { get; set; }
        public string PMTCT_EID_charts { get; set; }
        public string PMTCT_ARV_Charts { get; set; }
        public string TX_NEW_charts { get; set; }
        public string TX_CURR_charts { get; set; }
        public string HTC_Charts_Precisions { get; set; }
        public string PMTCT_STAT_Charts_Precisions { get; set; }
        public string PMTCT_EID_Charts_Precisions { get; set; }
        public string PMTCT_ARV_Charts_Precisions { get; set; }
        public string TX_NEW_Charts_Precisions { get; set; }
        public string TX_CURR_Charts_Precisions { get; set; }
        public string Total_Completeness_HTC_TST { get; set; }
        public string Total_Completeness_PMTCT_STAT { get; set; }
        public string Total_completeness_PMTCT_EID { get; set; }
        public string Total_completeness_PMTCT_ARV { get; set; }
        public string Total_completeness_TX_NEW { get; set; }
        public string Total_completeness_TX_CURR { get; set; }
        public string Total_consistency_HTC_TST { get; set; }
        public string Total_consistency_PMTCT_STAT { get; set; }
        public string Total_consistency_PMTCT_EID { get; set; }
        public string Total_consistency_PMTCT_ART { get; set; }
        public string Total_consistency_TX_NEW { get; set; }
        public string Total_consistency_TX_Curr { get; set; }
        public string Total_precision_HTC_TST { get; set; }
        public string Total_precision_PMTCT_STAT { get; set; }
        public string Total_precision_PMTCT_EID { get; set; }
        public string Total_precision_PMTCT_ARV { get; set; }
        public string Total_precision_TX_NEW { get; set; }
        public string Total_precision_TX_CURR { get; set; }
        public string Total_integrity_HTC_TST { get; set; }
        public string Total_integrity_PMTCT_STAT { get; set; }
        public string Total_integrity_PMTCT_EID { get; set; }
        public string Total_integrity_PMTCT_ART { get; set; }
        public string Total_integrity_TX_NEW { get; set; }
        public string Total_integrity_TX_Curr { get; set; }
        public string Total_Validity_HTC_TST { get; set; }
        public string Total_Validity_PMTCT_STAT { get; set; }
        public string Total_Validity_PMTCT_EID { get; set; }
        public string Total_Validity_PMTCT_ART { get; set; }
        public string Total_Validity_TX_NEW { get; set; }
        public string Total_Validity_TX_Curr { get; set; }
        public int MetadataId { get; set; }
    }
}
