//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DQA.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class dqa_comparison
    {
        public int Id { get; set; }
        public string FacilityName { get; set; }
        public string FacilityCode { get; set; }
        public int metadataId { get; set; }
        public string Datim_HTC_TST { get; set; }
        public string DATIM_HTC_TST_POS { get; set; }
        public string DATIM_HTC_ONLY { get; set; }
        public string DATIM_HTC_POS { get; set; }
        public string DATIM_PMTCT_STAT { get; set; }
        public string DATIM_PMTCT_STAT_POS { get; set; }
        public string DATIM_PMTCT_STAT_Previously { get; set; }
        public string DATIM_PMTCT_EID { get; set; }
        public string DATIM_PMTCT_ART { get; set; }
        public string Datim_TX_NEW { get; set; }
        public string DATIM_TX_CURR { get; set; }
        public string HTC_TST { get; set; }
        public string HTC_TST_POS { get; set; }
        public string HTC_ONLY { get; set; }
        public string HTC_POS { get; set; }
        public string PMTCT_STAT { get; set; }
        public string PMTCT_STAT_POS { get; set; }
        public string PMTCT_STAT_Previoulsy_Known { get; set; }
        public string PMTCT_EID { get; set; }
        public string PMTCT_ART { get; set; }
        public string TX_NEW { get; set; }
        public string TX_Curr { get; set; }
    }
}
