//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DQA.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class dqa_pivot_table_upload
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dqa_pivot_table_upload()
        {
            this.dqa_pivot_table = new HashSet<dqa_pivot_table>();
        }
    
        public int Id { get; set; }
        public int IP { get; set; }
        public string Quarter { get; set; }
        public int Year { get; set; }
        public System.DateTime DateUploaded { get; set; }
        public System.Guid UploadedBy { get; set; }
    
        public virtual ImplementingPartner ImplementingPartner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dqa_pivot_table> dqa_pivot_table { get; set; }
    }
}
