//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DQA.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class dqa_facility
    {
        public int Id { get; set; }
        public Nullable<double> State { get; set; }
        public string Site_Name { get; set; }
        public Nullable<double> Site_Ref__ID { get; set; }
        public string LGA { get; set; }
        public string Point_of_Service { get; set; }
        public string PEPFAR_Support { get; set; }
        public string Address { get; set; }
        public string Facility_Category { get; set; }
        public Nullable<double> Facility_Type { get; set; }
        public Nullable<double> Facility_Level { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<double> Funder { get; set; }
        public Nullable<double> Partners { get; set; }
        public Nullable<double> HQR_Mechanism_ID { get; set; }
        public string Coag_Number { get; set; }
        public Nullable<double> Start_Date { get; set; }
        public Nullable<double> End_Date { get; set; }
        public string Coag_PO { get; set; }
        public Nullable<double> EMR { get; set; }
        public Nullable<double> PMTCT { get; set; }
        public Nullable<double> AB { get; set; }
        public Nullable<double> PEP { get; set; }
        public Nullable<double> C_OP { get; set; }
        public Nullable<double> Blood_Safety { get; set; }
        public Nullable<double> C_Injection_Safety { get; set; }
        public Nullable<double> Med_Waste_Management { get; set; }
        public Nullable<double> HCT_hospital_based { get; set; }
        public string HCT_stand_alone { get; set; }
        public string HCT_mobile { get; set; }
        public string HCT_home_based { get; set; }
        public Nullable<double> C_S { get; set; }
        public Nullable<double> TB_HIV { get; set; }
        public Nullable<double> OVC { get; set; }
        public Nullable<double> Treatment { get; set; }
        public Nullable<double> HSS_Lab__clinical { get; set; }
        public Nullable<double> HSS_Lab_point_of_care { get; set; }
        public Nullable<double> HSS__Supply_Chain { get; set; }
        public Nullable<double> QI_QM { get; set; }
        public string Support_Group { get; set; }
        public string Gen_pop__youth { get; set; }
        public Nullable<double> Key_pop { get; set; }
        public Nullable<double> Gender { get; set; }
        public Nullable<double> PHDP_Family_Planning_Integration { get; set; }
        public Nullable<double> Food___Nutrition { get; set; }
    }
}
