//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DQA.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class dqi_report_value
    {
        public int Id { get; set; }
        public string ImplementingPartner { get; set; }
        public string DqaIndicator { get; set; }
        public string AffectedFacilityNumber { get; set; }
        public string ImprovementApproach { get; set; }
        public string DataCollectionMethod { get; set; }
        public string Problem { get; set; }
        public string ProblemResolved { get; set; }
        public string WhyDoesProblemOccur { get; set; }
        public string ImprovementApproach_Analyze { get; set; }
        public string Interventions { get; set; }
        public string ImprovementApproach_Develop { get; set; }
        public string ProcessTracking { get; set; }
        public string MeasureIndicators { get; set; }
        public string EvaluateIndicators { get; set; }
        public string Indicators { get; set; }
        public string ReportPeriod { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public string uploadedBy { get; set; }
    
        public virtual dqi_report_value dqi_report_value1 { get; set; }
        public virtual dqi_report_value dqi_report_value2 { get; set; }
    }
}
