//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DQA.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthFacility
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HealthFacility()
        {
            this.dqa_pivot_table = new HashSet<dqa_pivot_table>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string FacilityCode { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string LGAId { get; set; }
        public string OrganizationType { get; set; }
        public Nullable<int> ImplementingPartnerId { get; set; }
        public string LinkCode { get; set; }
        public Nullable<int> Previous_IP { get; set; }
    
        public virtual lga lga { get; set; }
        public virtual ImplementingPartner ImplementingPartner { get; set; }
        public virtual lga lga1 { get; set; }
        public virtual ImplementingPartner ImplementingPartner1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dqa_pivot_table> dqa_pivot_table { get; set; }
        public virtual ImplementingPartner ImplementingPartner2 { get; set; }
        public virtual ImplementingPartner ImplementingPartner3 { get; set; }
    }
}
