//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DQA.DAL.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class shield_dmpEntities : DbContext
    {
        public shield_dmpEntities()
            : base("name=shield_dmpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dmp_Organizations> dmp_Organizations { get; set; }
        public virtual DbSet<dqa_facility> dqa_facility { get; set; }
        public virtual DbSet<dqa_facility_level> dqa_facility_level { get; set; }
        public virtual DbSet<dqa_facility_type> dqa_facility_type { get; set; }
        public virtual DbSet<dqa_funder> dqa_funder { get; set; }
        public virtual DbSet<dqa_indicator> dqa_indicator { get; set; }
        public virtual DbSet<dqa_lga> dqa_lga { get; set; }
        public virtual DbSet<dqa_report_value> dqa_report_value { get; set; }
        public virtual DbSet<dqa_states> dqa_states { get; set; }
        public virtual DbSet<dqa_report_metadata> dqa_report_metadata { get; set; }
    }
}
